version: '3.8'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - "8089:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
